manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    - name: jasoncronje
      url-base: https://github.com/jasoncronje
  projects:
    - name: zmk
      remote: jasoncronje
      revision: 1358d5aee2f4abc3ab8a263224bba49846fbb5f8
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: 5e04553ab803d24405bd45621a41310ea3050e59
    - name: zmk-nice-oled
      remote: jasoncronje
      revision: 2fb1e98b9f60c57ed0d541e08d998f869a224dd9
  self:
    path: config
